# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_bus', models.CharField(choices=[('Volvo', 'Volvo'), ('Ordinary', 'Ordinary')], max_length=255)),
                ('bus_registration', models.CharField(default='', max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('bus_number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequency_id', models.AutoField(primary_key=True, serialize=False)),
                ('Monday', models.TimeField(blank=True, null=True)),
                ('Tuesday', models.TimeField(blank=True, null=True)),
                ('Wednesday', models.TimeField(blank=True, null=True)),
                ('Thursday', models.TimeField(blank=True, null=True)),
                ('Friday', models.TimeField(blank=True, null=True)),
                ('Saturday', models.TimeField(blank=True, null=True)),
                ('Sunday', models.TimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Bus')),
            ],
            options={
                'verbose_name_plural': 'Frequncy',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_from', models.CharField(choices=[('Delhi', 'Delhi'), ('Jaipur', 'Jaipur'), ('Ajmer', 'Ajmer')], max_length=255)),
                ('location_to', models.CharField(choices=[('Ajmer', 'Ajmer'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Route'),
        ),
    ]
