# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170428_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(choices=[('35', '35'), ('31', '31')], default=35),
        ),
    ]
