# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170428_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
