# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
