# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170428_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
    ]
