# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170501_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_label',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('reserved', 'reserved'), ('unavailable', 'unavailable')], default='available', max_length=20),
        ),
    ]
