# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20170514_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='book',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.Booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
